// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file proto/poky/v1/webpush_service.proto (package proto.poky.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/poky/v1/webpush_service.proto.
 */
export const file_proto_poky_v1_webpush_service: GenFile = /*@__PURE__*/
  fileDesc("CiNwcm90by9wb2t5L3YxL3dlYnB1c2hfc2VydmljZS5wcm90bxINcHJvdG8ucG9reS52MSLeAQoWUmVnaXN0ZXJXZWJQdXNoUmVxdWVzdBIQCghlbmRwb2ludBgBIAEoCRIcCg9leHBpcmF0aW9uX3RpbWUYAiABKANIAIgBARIPCgdvcHRpb25zGAMgASgJEgoKAmlkGAQgASgJEhEKCWRldmljZV9pZBgFIAEoCRIYCgtkZXZpY2VfbmFtZRgGIAEoCUgBiAEBEhcKCnVzZXJfYWdlbnQYByABKAlIAogBAUISChBfZXhwaXJhdGlvbl90aW1lQg4KDF9kZXZpY2VfbmFtZUINCgtfdXNlcl9hZ2VudCIqChdSZWdpc3RlcldlYlB1c2hSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIh8KEUdldFdlYlB1c2hSZXF1ZXN0EgoKAmlkGAEgASgJIpkBChJHZXRXZWJQdXNoUmVzcG9uc2USCgoCaWQYASABKAkSEAoIZW5kcG9pbnQYAiABKAkSHAoPZXhwaXJhdGlvbl90aW1lGAMgASgDSACIAQESDwoHb3B0aW9ucxgEIAEoCRIPCgd1c2VyX2lkGAUgASgJEhEKCWRldmljZV9pZBgGIAEoCUISChBfZXhwaXJhdGlvbl90aW1lIiIKFERlbGV0ZVdlYlB1c2hSZXF1ZXN0EgoKAmlkGAEgASgJIigKFURlbGV0ZVdlYlB1c2hSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIicKElRlc3RXZWJQdXNoUmVxdWVzdBIRCglkZXZpY2VfaWQYASABKAkiNwoTVGVzdFdlYlB1c2hSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB3NlbnRfdG8YAiABKAUy9wIKDldlYlB1c2hTZXJ2aWNlEmAKD1JlZ2lzdGVyV2ViUHVzaBIlLnByb3RvLnBva3kudjEuUmVnaXN0ZXJXZWJQdXNoUmVxdWVzdBomLnByb3RvLnBva3kudjEuUmVnaXN0ZXJXZWJQdXNoUmVzcG9uc2USUQoKR2V0V2ViUHVzaBIgLnByb3RvLnBva3kudjEuR2V0V2ViUHVzaFJlcXVlc3QaIS5wcm90by5wb2t5LnYxLkdldFdlYlB1c2hSZXNwb25zZRJaCg1EZWxldGVXZWJQdXNoEiMucHJvdG8ucG9reS52MS5EZWxldGVXZWJQdXNoUmVxdWVzdBokLnByb3RvLnBva3kudjEuRGVsZXRlV2ViUHVzaFJlc3BvbnNlElQKC1Rlc3RXZWJQdXNoEiEucHJvdG8ucG9reS52MS5UZXN0V2ViUHVzaFJlcXVlc3QaIi5wcm90by5wb2t5LnYxLlRlc3RXZWJQdXNoUmVzcG9uc2ViBnByb3RvMw");

/**
 * ----- Register -----
 *
 * @generated from message proto.poky.v1.RegisterWebPushRequest
 */
export type RegisterWebPushRequest = Message<"proto.poky.v1.RegisterWebPushRequest"> & {
  /**
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;

  /**
   * @generated from field: optional int64 expiration_time = 2;
   */
  expirationTime?: bigint;

  /**
   * @generated from field: string options = 3;
   */
  options: string;

  /**
   * @generated from field: string id = 4;
   */
  id: string;

  /**
   * @generated from field: string device_id = 5;
   */
  deviceId: string;

  /**
   * @generated from field: optional string device_name = 6;
   */
  deviceName?: string;

  /**
   * @generated from field: optional string user_agent = 7;
   */
  userAgent?: string;
};

/**
 * Describes the message proto.poky.v1.RegisterWebPushRequest.
 * Use `create(RegisterWebPushRequestSchema)` to create a new message.
 */
export const RegisterWebPushRequestSchema: GenMessage<RegisterWebPushRequest> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 0);

/**
 * @generated from message proto.poky.v1.RegisterWebPushResponse
 */
export type RegisterWebPushResponse = Message<"proto.poky.v1.RegisterWebPushResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message proto.poky.v1.RegisterWebPushResponse.
 * Use `create(RegisterWebPushResponseSchema)` to create a new message.
 */
export const RegisterWebPushResponseSchema: GenMessage<RegisterWebPushResponse> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 1);

/**
 * ----- Get -----
 *
 * @generated from message proto.poky.v1.GetWebPushRequest
 */
export type GetWebPushRequest = Message<"proto.poky.v1.GetWebPushRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message proto.poky.v1.GetWebPushRequest.
 * Use `create(GetWebPushRequestSchema)` to create a new message.
 */
export const GetWebPushRequestSchema: GenMessage<GetWebPushRequest> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 2);

/**
 * @generated from message proto.poky.v1.GetWebPushResponse
 */
export type GetWebPushResponse = Message<"proto.poky.v1.GetWebPushResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string endpoint = 2;
   */
  endpoint: string;

  /**
   * @generated from field: optional int64 expiration_time = 3;
   */
  expirationTime?: bigint;

  /**
   * @generated from field: string options = 4;
   */
  options: string;

  /**
   * @generated from field: string user_id = 5;
   */
  userId: string;

  /**
   * @generated from field: string device_id = 6;
   */
  deviceId: string;
};

/**
 * Describes the message proto.poky.v1.GetWebPushResponse.
 * Use `create(GetWebPushResponseSchema)` to create a new message.
 */
export const GetWebPushResponseSchema: GenMessage<GetWebPushResponse> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 3);

/**
 * ----- Delete -----
 *
 * @generated from message proto.poky.v1.DeleteWebPushRequest
 */
export type DeleteWebPushRequest = Message<"proto.poky.v1.DeleteWebPushRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message proto.poky.v1.DeleteWebPushRequest.
 * Use `create(DeleteWebPushRequestSchema)` to create a new message.
 */
export const DeleteWebPushRequestSchema: GenMessage<DeleteWebPushRequest> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 4);

/**
 * @generated from message proto.poky.v1.DeleteWebPushResponse
 */
export type DeleteWebPushResponse = Message<"proto.poky.v1.DeleteWebPushResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message proto.poky.v1.DeleteWebPushResponse.
 * Use `create(DeleteWebPushResponseSchema)` to create a new message.
 */
export const DeleteWebPushResponseSchema: GenMessage<DeleteWebPushResponse> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 5);

/**
 * ----- Test -----
 *
 * @generated from message proto.poky.v1.TestWebPushRequest
 */
export type TestWebPushRequest = Message<"proto.poky.v1.TestWebPushRequest"> & {
  /**
   * @generated from field: string device_id = 1;
   */
  deviceId: string;
};

/**
 * Describes the message proto.poky.v1.TestWebPushRequest.
 * Use `create(TestWebPushRequestSchema)` to create a new message.
 */
export const TestWebPushRequestSchema: GenMessage<TestWebPushRequest> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 6);

/**
 * @generated from message proto.poky.v1.TestWebPushResponse
 */
export type TestWebPushResponse = Message<"proto.poky.v1.TestWebPushResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: int32 sent_to = 2;
   */
  sentTo: number;
};

/**
 * Describes the message proto.poky.v1.TestWebPushResponse.
 * Use `create(TestWebPushResponseSchema)` to create a new message.
 */
export const TestWebPushResponseSchema: GenMessage<TestWebPushResponse> = /*@__PURE__*/
  messageDesc(file_proto_poky_v1_webpush_service, 7);

/**
 * @generated from service proto.poky.v1.WebPushService
 */
export const WebPushService: GenService<{
  /**
   * @generated from rpc proto.poky.v1.WebPushService.RegisterWebPush
   */
  registerWebPush: {
    methodKind: "unary";
    input: typeof RegisterWebPushRequestSchema;
    output: typeof RegisterWebPushResponseSchema;
  },
  /**
   * @generated from rpc proto.poky.v1.WebPushService.GetWebPush
   */
  getWebPush: {
    methodKind: "unary";
    input: typeof GetWebPushRequestSchema;
    output: typeof GetWebPushResponseSchema;
  },
  /**
   * @generated from rpc proto.poky.v1.WebPushService.DeleteWebPush
   */
  deleteWebPush: {
    methodKind: "unary";
    input: typeof DeleteWebPushRequestSchema;
    output: typeof DeleteWebPushResponseSchema;
  },
  /**
   * @generated from rpc proto.poky.v1.WebPushService.TestWebPush
   */
  testWebPush: {
    methodKind: "unary";
    input: typeof TestWebPushRequestSchema;
    output: typeof TestWebPushResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_poky_v1_webpush_service, 0);

