services:
  redis:
    image: redis:7-alpine
    container_name: reddit_redis
    ports:
      - "6379:6379"
    command: redis-server
    restart: unless-stopped
    networks:
      - network

  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: reddit_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
