services:
  nats:
    image: nats:2.10-alpine
    container_name: poky_nats
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - network

  valkey:
    image: valkey/valkey:7-alpine
    container_name: poky_valkey
    ports:
      - "6379:6379"
    command: valkey-server
    restart: unless-stopped
    networks:
      - network

  postgres:
    image: postgres:17
    container_name: reddit_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "8001:5432"
    volumes:
      - /tmp/postgres_data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
